= Security and Governance


== Security & RBAC

* Each user is assigned a dedicated project in *OpenShift Dev Spaces* to host their workspaces.
* Projects can be assigned either automatically by *OpenShift Dev Spaces* or through the use of project templates to allow for more control and policy enforcement, as we will explore in upcoming labs.
* Each user is granted permissions only to their own project, meaning they cannot access other users’ resources.
* Administrators can set up granular access controls for different groups and users by adding the following configuration to the OpenShift Dev Spaces Custom Resource:

```yaml
 networking:
    auth:
      advancedAuthorization:
        allowUsers:
          - user-a
          - user-b
        denyUsers:
          - user-c
        allowGroups:
          - team-a
          - team-b
        denyGroups:          
          - team-c
```

== Lab 3.1 Setup Granular Access

* In this lab, we will configure granular access to OpenShift Dev Spaces. Specifically, we will allow access for *Eddie* while denying access for *Ella*.

networking:
    auth:
      advancedAuthorization:
        allowUsers:
          - eddie
        denyUsers:
          - ella
       


== Optimizing Resources

== Enforcing Polices

=== Disable Auto Provisioning 

By default, OpenShift Dev Spaces will provision a unique <username>-devspaces project for each user. Alternatively, the cluster administrator can disable project self-provisioning on the OpenShift level, and turn off automatic namespace provisioning in the CheCluster custom resource:

devEnvironments:
  defaultNamespace:
    autoProvision: false

This setup allows achieving curated access to the Dev Spaces, where cluster administrators control provisioning for each user and can explicitly configure various settings including resource limits and quotas.


* PVC Strategy
* No of running wrokspaces
* Stop Autoprovisioning
* NaaS -> create onboarding project with project template