= Security and Governance


== Security & RBAC

Each user is assinged a project in OpenShift Dev Spaces to host their workspaces.
Projects can be assigned by OpenShift Dev Spaces autontically or can be assigned through the use of projects templates to allow for more control and policy enforcemnts as we will see in the coming labs.
Each user is granted permissions only to their project, and will not be able to access other user’s resources.
Only authenticated OpenShift users can access Red Hat OpenShift Dev Spaces. The Gateway Pod rejects unauthenticated users
Users who are not allowed will not be able to use Red Hat OpenShift Dev Spaces and will see the warning shown in this figure
Admins can setup  up granular access for different groups and users by adding this configuration to the OpenShift Dev Spaces Custom Resource:

 networking:
    auth:
      advancedAuthorization:
        allowUsers:
          - user-a
          - user-b
        denyUsers:
          - user-c
        allowGroups:
          - team-a
          - team-b
        denyGroups:          
          - team-c

== Lab 3.1 Setup Granular Access

* In this lab we will allow access to eddie while denying ella access to OpenShift Dev Spaces.

networking:
    auth:
      advancedAuthorization:
        allowUsers:
          - eddie
        denyUsers:
          - ella
       


== Optimizing Resources

== Enforcing Polices

=== Disable Auto Provisioning 

By default, OpenShift Dev Spaces will provision a unique <username>-devspaces project for each user. Alternatively, the cluster administrator can disable project self-provisioning on the OpenShift level, and turn off automatic namespace provisioning in the CheCluster custom resource:

devEnvironments:
  defaultNamespace:
    autoProvision: false

This setup allows achieving curated access to the Dev Spaces, where cluster administrators control provisioning for each user and can explicitly configure various settings including resource limits and quotas.


* PVC Strategy
* Add project to sample project?
* No of running wrokspaces
* Switch to intelliJ
* Stop Autoprovisioning
* NaaS -> create onboarding project with project template